### PR TITLE
Added favicons

### PR DESCRIPTION
**Pull request by arthurmatthew**
As requested in issue #3 , I have added a custom favicon to the webpage. I've made sure that the favicon looks good and works as intended on all devices.

Additions:
- Special favicon for iOS and Android home screens
- Special favicon for Windows 8+ tiles
- Specially configured for more situations where it may look bad
- Multiple favicon sizes for different situations

### CODE REVIEW

**Comment by arthurmatthew** [comment]
Analysis of favicon checks out on [this favicon checker website](https://realfavicongenerator.net/favicon_checker?protocol=https&site=deploy-preview-11--sanket1308-weather-app.netlify.app%2F#.YzkM9HbMKUk).

**Comment by boradesanket13** [comment]
Good work, @arthurmatthew! Design could be better. Black background doesn't suits well. Make changes and share design here in discussion before you start working on it.🚀

**Comment by arthurmatthew** [comment]
> Good work, @arthurmatthew! Design could be better. Black background doesn't suits well. Make changes and share design here in discussion before you start working on it.🚀

Thanks for the feedback! What do you think I should do instead? I could go for no background, or a color of your choice. I was just thinking that the black background would help users see if their browser was on light mode.

**Comment by arthurmatthew** [comment]
I noticed that you've merged another PR with different favicons. I'm going to close this one. Thanks!

**Pull request closed without merging**
